FROM eclipse-temurin:17-jdk

# Instalar Graphviz para generación de diagramas
RUN apt-get update && apt-get install -y graphviz && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src

RUN chmod +x mvnw
RUN ./mvnw dependency:go-offline

RUN ./mvnw clean compile -DskipTests

EXPOSE 8080

CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.fork=false"]
